server:
  port: 9506
  servlet:
    context-path: /bank


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Bank
    username: postgres
    password: hoxa-95-hoxa
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: Bank
        dialect: org.hibernate.dialect.PostgresPlusDialect
        hbm2ddl:
          auto: update
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    encoding: UTF-8

account:
  default-sum: 1000

jwt:
  secret: Z29yZXRz
  life-time: 30m